/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import negocio.AdministradorInt;

/**
 *
 * @author Felipe Mora
 */
public class ListaGeneral extends javax.swing.JFrame {

    AdministradorInt admin;
    
    /**
     * Creates new form ListaGeneral
     */
    public ListaGeneral() {
        initComponents();
    }
    
    public ListaGeneral(AdministradorInt p_Admin)
    {
        initComponents();
        admin = p_Admin;
    }

    public void setTxt_BolSist(String num) {
        this.txt_BolSist.setText(num);
    }

    public void setTxt_Boletas(String boletas) {
        this.txt_Boletas.setText(boletas);
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Boletas = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        txt_BolSist = new javax.swing.JTextField();
        btn_Alf = new javax.swing.JButton();
        btn_Admitidos = new javax.swing.JButton();
        btn_ElRe = new javax.swing.JButton();
        btn_Mejores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Total de boletas en el sistema");

        txt_Boletas.setColumns(20);
        txt_Boletas.setRows(5);
        jScrollPane1.setViewportView(txt_Boletas);

        jButton1.setText("Obtener Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_BolSist.setEditable(false);

        btn_Alf.setText("Ordenar Alfabeticamente");
        btn_Alf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlfActionPerformed(evt);
            }
        });

        btn_Admitidos.setText("Ranking Admitidos");
        btn_Admitidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdmitidosActionPerformed(evt);
            }
        });

        btn_ElRe.setText("Elegibles / Rechazados");
        btn_ElRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ElReActionPerformed(evt);
            }
        });

        btn_Mejores.setText("3 Mejores Promedios");
        btn_Mejores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MejoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_BolSist, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Alf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Admitidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ElRe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Mejores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(txt_BolSist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Alf)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Admitidos)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ElRe)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Mejores)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        int code = admin.obtenerBoletas(this);
        if ((code == 0) && ("0".equals(txt_BolSist.getText())))
        {
            JOptionPane.showMessageDialog(null, "No existen boletas en el sistema");
            txt_Boletas.setText("");
        }   
        else 
            JOptionPane.showMessageDialog(null, "Boletas cargadas con éxito");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //Ranking admitidos
    private void btn_AdmitidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdmitidosActionPerformed
        // TODO add your handling code here:
        admin.rankingAdmitidos(this);
    }//GEN-LAST:event_btn_AdmitidosActionPerformed

    //Elegibles/Rechazados
    private void btn_ElReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ElReActionPerformed
        admin.obtenerElegibles_Rechazados(this);
    }//GEN-LAST:event_btn_ElReActionPerformed

    //boton alfabeticamente
    private void btn_AlfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlfActionPerformed
        // TODO add your handling code here:
        admin.ordenarAlfab(this);
    }//GEN-LAST:event_btn_AlfActionPerformed
    
    //Mejores promedios
    private void btn_MejoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MejoresActionPerformed
        // TODO add your handling code here:
        admin.obtenerTresMej(this);
    }//GEN-LAST:event_btn_MejoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Admitidos;
    private javax.swing.JButton btn_Alf;
    private javax.swing.JButton btn_ElRe;
    private javax.swing.JButton btn_Mejores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_BolSist;
    private javax.swing.JTextArea txt_Boletas;
    // End of variables declaration//GEN-END:variables
}
